name: build-publish

on: 
  push:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 4 * * 1"

jobs:
  build:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    
    steps:
       ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - run: build.sh